### ISSUE TITLE
Any interest / plans to support REST APIs

### ISSUE THREAD

**Issue by bibliotechy** [NYULibraries/exlibris-primo#4]
This lib looks great, thanks for maintaining it. 

We're looking at the Primo REST APIs so we can avoid dealing with whitelisting IPs. Is that anywhere on your roadmap? We (at Temple) would be happy to contribute dev cycles if that's something y'all are planning, or have ideas about.

**Comment by barnabyalter** [comment]
Hey @bibliotechy, thanks for reaching out. Though there is no formal road map this is a legacy library for us and using the REST APIs for future projects is preferred. I'd like to shift away from a wrapper for everything primo and begin developing modular libraries for individual components of the REST API. We can also build them out as we need to use them which is an easier endeavor than rewriting this library. I think we'll have a use case for this in the next several months but currently that's pretty vague.

**Comment by bibliotechy** [comment]
@barnabyalter OK, interesting. I'd love to hear more about your modular structure. We're going to be working with the Primo REST Api in the next few weeks, so we will be putting something together for the PNX search and item detail endpoints to start with. 

We have started working on an [alma](https://github.com/tulibraries/alma_rb) api wrapper that's meant to be pretty light weight and unopinionated, but it is still WIP. We're doing users, bibs, acquisitions, etc in the same gem, just separated classes. Our Primo work will probably follow a similar pattern. Would be great to chat at some point about seeing if there is room for shared dev.

**Comment by barnabyalter** [comment]
@bibliotechy no current road map for this so closing for now

**Comment by bibliotechy** [comment]
@barnabyalter Just a note to say that we have been working on client REST search and PNX endpoints  at https://github.com/tulibraries/primo/
